version: "3.9"
services:
  application:
    container_name: application
    build: .
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
